"use client";

import type { AiPass } from "@diffsync/protocol";

/**
 * Renders nothing at all when there is no pass -- no empty box, no spinner.
 * With no provider configured this component is invisible and the review
 * surface is complete without it.
 *
 * When it does render it is set apart from every other card in the app:
 * dashed rule, sunken surface, no accent colour, and its heading names the
 * model. Generative AI, Transparency -- "never trick someone into thinking
 * they're interacting with or viewing content authored by a human" -- so
 * model output must not be mistakable for a reviewer's thread at a glance.
 */
export function AiPanel({ pass }: { pass: AiPass | null }): React.JSX.Element | null {
  if (pass === null) return null;

  return (
    <section data-testid="ai-panel" aria-label="Model output" className="ai-panel">
      <h2 className="ai-panel__title">{`Model output (${pass.generatedBy})`}</h2>
      <p className="ai-panel__disclaimer">
        Generated by a language model. A suggested reading order, not a review.
      </p>
      <p data-testid="ai-summary" className="ai-panel__summary">
        {pass.summary}
      </p>
      <ol role="list" className="ai-panel__flags">
        {pass.flags.map((flag, index) => (
          <li
            key={`${flag.path}-${flag.hunkIndex}`}
            data-testid={`ai-flag-${index}`}
            className="ai-panel__flag"
          >
            <strong>{`${flag.path} (hunk ${flag.hunkIndex + 1})`}</strong>
            <span>{` — ${flag.reason}`}</span>
          </li>
        ))}
      </ol>
    </section>
  );
}
