"use client";

import type { AiPass } from "@diffsync/protocol";

/**
 * Renders nothing at all when there is no pass -- no empty box, no spinner.
 * With no provider configured this component is invisible and the review
 * surface is complete without it.
 */
export function AiPanel({ pass }: { pass: AiPass | null }): React.JSX.Element | null {
  if (pass === null) return null;

  return (
    <section data-testid="ai-panel" aria-label="Model output">
      <h2>{`Model output (${pass.generatedBy})`}</h2>
      <p>Generated by a language model. A suggested reading order, not a review.</p>
      <p data-testid="ai-summary">{pass.summary}</p>
      <ol>
        {pass.flags.map((flag, index) => (
          <li key={`${flag.path}-${flag.hunkIndex}`} data-testid={`ai-flag-${index}`}>
            <strong>{`${flag.path} (hunk ${flag.hunkIndex + 1})`}</strong>
            <span>{` — ${flag.reason}`}</span>
          </li>
        ))}
      </ol>
    </section>
  );
}
